// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/dashboard": {
    params: {};
  };
  "/insights": {
    params: {};
  };
  "/insights/productivity": {
    params: {};
  };
  "/insights/port-performance": {
    params: {};
  };
  "/insights/staff-performance": {
    params: {};
  };
  "/insights/storage-utilization": {
    params: {};
  };
  "/insights/replenishment": {
    params: {};
  };
  "/insights/system-health": {
    params: {};
  };
  "/inbound": {
    params: {};
  };
  "/inbound/putaway": {
    params: {};
  };
  "/outbound": {
    params: {};
  };
  "/outbound/picking": {
    params: {};
  };
  "/outbound/order-batching": {
    params: {};
  };
  "/outbound/picking-strategies": {
    params: {};
  };
  "/outbound/printing": {
    params: {};
  };
  "/inventory": {
    params: {};
  };
  "/inventory/inspection": {
    params: {};
  };
  "/control-center": {
    params: {};
  };
  "/control-center/alert-monitoring": {
    params: {};
  };
  "/control-center/orders-tracking": {
    params: {};
  };
  "/control-center/eoperator-console": {
    params: {};
  };
  "/control-center/maintenance": {
    params: {};
  };
  "/control-center/integration-logs": {
    params: {};
  };
  "/control-center/system-logs": {
    params: {};
  };
  "/control-center/material-handling-logs": {
    params: {};
  };
  "/configuration": {
    params: {};
  };
  "/configuration/language-settings": {
    params: {};
  };
  "/configuration/system-settings": {
    params: {};
  };
  "/configuration/inbound": {
    params: {};
  };
  "/configuration/outbound": {
    params: {};
  };
  "/configuration/inventory": {
    params: {};
  };
  "/configuration/autostore": {
    params: {};
  };
  "/configuration/general-setup": {
    params: {};
  };
  "/configuration/modules": {
    params: {};
  };
  "/configuration/orchestration": {
    params: {};
  };
  "/configuration/version-history": {
    params: {};
  };
  "/profile": {
    params: {};
  };
  "/profile/system-preferences": {
    params: {};
  };
  "/profile/security": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/dashboard" | "/insights" | "/insights/productivity" | "/insights/port-performance" | "/insights/staff-performance" | "/insights/storage-utilization" | "/insights/replenishment" | "/insights/system-health" | "/inbound" | "/inbound/putaway" | "/outbound" | "/outbound/picking" | "/outbound/order-batching" | "/outbound/picking-strategies" | "/outbound/printing" | "/inventory" | "/inventory/inspection" | "/control-center" | "/control-center/alert-monitoring" | "/control-center/orders-tracking" | "/control-center/eoperator-console" | "/control-center/maintenance" | "/control-center/integration-logs" | "/control-center/system-logs" | "/control-center/material-handling-logs" | "/configuration" | "/configuration/language-settings" | "/configuration/system-settings" | "/configuration/inbound" | "/configuration/outbound" | "/configuration/inventory" | "/configuration/autostore" | "/configuration/general-setup" | "/configuration/modules" | "/configuration/orchestration" | "/configuration/version-history" | "/profile" | "/profile/system-preferences" | "/profile/security";
  };
  "routes/dashboard.tsx": {
    id: "routes/dashboard";
    page: "/dashboard";
  };
  "routes/insights.tsx": {
    id: "routes/insights";
    page: "/insights" | "/insights/productivity" | "/insights/port-performance" | "/insights/staff-performance" | "/insights/storage-utilization" | "/insights/replenishment" | "/insights/system-health";
  };
  "routes/insights.overview.tsx": {
    id: "routes/insights.overview";
    page: "/insights";
  };
  "routes/insights.productivity.tsx": {
    id: "routes/insights.productivity";
    page: "/insights/productivity";
  };
  "routes/insights.port-performance.tsx": {
    id: "routes/insights.port-performance";
    page: "/insights/port-performance";
  };
  "routes/insights.staff-performance.tsx": {
    id: "routes/insights.staff-performance";
    page: "/insights/staff-performance";
  };
  "routes/insights.storage-utilization.tsx": {
    id: "routes/insights.storage-utilization";
    page: "/insights/storage-utilization";
  };
  "routes/insights.replenishment.tsx": {
    id: "routes/insights.replenishment";
    page: "/insights/replenishment";
  };
  "routes/insights.system-health.tsx": {
    id: "routes/insights.system-health";
    page: "/insights/system-health";
  };
  "routes/inbound.tsx": {
    id: "routes/inbound";
    page: "/inbound" | "/inbound/putaway";
  };
  "routes/inbound.overview.tsx": {
    id: "routes/inbound.overview";
    page: "/inbound";
  };
  "routes/inbound.putaway.tsx": {
    id: "routes/inbound.putaway";
    page: "/inbound/putaway";
  };
  "routes/outbound.tsx": {
    id: "routes/outbound";
    page: "/outbound" | "/outbound/picking" | "/outbound/order-batching" | "/outbound/picking-strategies" | "/outbound/printing";
  };
  "routes/outbound.overview.tsx": {
    id: "routes/outbound.overview";
    page: "/outbound";
  };
  "routes/outbound.picking.tsx": {
    id: "routes/outbound.picking";
    page: "/outbound/picking";
  };
  "routes/outbound.order-batching.tsx": {
    id: "routes/outbound.order-batching";
    page: "/outbound/order-batching";
  };
  "routes/outbound.picking-strategies.tsx": {
    id: "routes/outbound.picking-strategies";
    page: "/outbound/picking-strategies";
  };
  "routes/outbound.printing.tsx": {
    id: "routes/outbound.printing";
    page: "/outbound/printing";
  };
  "routes/inventory.tsx": {
    id: "routes/inventory";
    page: "/inventory" | "/inventory/inspection";
  };
  "routes/inventory.overview.tsx": {
    id: "routes/inventory.overview";
    page: "/inventory";
  };
  "routes/inventory.inspection.tsx": {
    id: "routes/inventory.inspection";
    page: "/inventory/inspection";
  };
  "routes/control-center.tsx": {
    id: "routes/control-center";
    page: "/control-center" | "/control-center/alert-monitoring" | "/control-center/orders-tracking" | "/control-center/eoperator-console" | "/control-center/maintenance" | "/control-center/integration-logs" | "/control-center/system-logs" | "/control-center/material-handling-logs";
  };
  "routes/control-center.warehouse-layout.tsx": {
    id: "routes/control-center.warehouse-layout";
    page: "/control-center";
  };
  "routes/control-center.alert-monitoring.tsx": {
    id: "routes/control-center.alert-monitoring";
    page: "/control-center/alert-monitoring";
  };
  "routes/control-center.orders-tracking.tsx": {
    id: "routes/control-center.orders-tracking";
    page: "/control-center/orders-tracking";
  };
  "routes/control-center.eoperator-console.tsx": {
    id: "routes/control-center.eoperator-console";
    page: "/control-center/eoperator-console";
  };
  "routes/control-center.maintenance.tsx": {
    id: "routes/control-center.maintenance";
    page: "/control-center/maintenance";
  };
  "routes/control-center.integration-logs.tsx": {
    id: "routes/control-center.integration-logs";
    page: "/control-center/integration-logs";
  };
  "routes/control-center.system-logs.tsx": {
    id: "routes/control-center.system-logs";
    page: "/control-center/system-logs";
  };
  "routes/control-center.material-handling-logs.tsx": {
    id: "routes/control-center.material-handling-logs";
    page: "/control-center/material-handling-logs";
  };
  "routes/configuration.tsx": {
    id: "routes/configuration";
    page: "/configuration" | "/configuration/language-settings" | "/configuration/system-settings" | "/configuration/inbound" | "/configuration/outbound" | "/configuration/inventory" | "/configuration/autostore" | "/configuration/general-setup" | "/configuration/modules" | "/configuration/orchestration" | "/configuration/version-history";
  };
  "routes/configuration.user-management.tsx": {
    id: "routes/configuration.user-management";
    page: "/configuration";
  };
  "routes/configuration.language-settings.tsx": {
    id: "routes/configuration.language-settings";
    page: "/configuration/language-settings";
  };
  "routes/configuration.system-settings.tsx": {
    id: "routes/configuration.system-settings";
    page: "/configuration/system-settings";
  };
  "routes/configuration.inbound.tsx": {
    id: "routes/configuration.inbound";
    page: "/configuration/inbound";
  };
  "routes/configuration.outbound.tsx": {
    id: "routes/configuration.outbound";
    page: "/configuration/outbound";
  };
  "routes/configuration.inventory.tsx": {
    id: "routes/configuration.inventory";
    page: "/configuration/inventory";
  };
  "routes/configuration.autostore.tsx": {
    id: "routes/configuration.autostore";
    page: "/configuration/autostore";
  };
  "routes/configuration.general-setup.tsx": {
    id: "routes/configuration.general-setup";
    page: "/configuration/general-setup";
  };
  "routes/configuration.modules.tsx": {
    id: "routes/configuration.modules";
    page: "/configuration/modules";
  };
  "routes/configuration.orchestration.tsx": {
    id: "routes/configuration.orchestration";
    page: "/configuration/orchestration";
  };
  "routes/configuration.version-history.tsx": {
    id: "routes/configuration.version-history";
    page: "/configuration/version-history";
  };
  "routes/profile.personal-information.tsx": {
    id: "routes/profile.personal-information";
    page: "/profile" | "/profile/system-preferences" | "/profile/security";
  };
  "routes/profile.system-preferences.tsx": {
    id: "routes/profile.system-preferences";
    page: "/profile/system-preferences";
  };
  "routes/profile.security.tsx": {
    id: "routes/profile.security";
    page: "/profile/security";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/dashboard": typeof import("./app/routes/dashboard.tsx");
  "routes/insights": typeof import("./app/routes/insights.tsx");
  "routes/insights.overview": typeof import("./app/routes/insights.overview.tsx");
  "routes/insights.productivity": typeof import("./app/routes/insights.productivity.tsx");
  "routes/insights.port-performance": typeof import("./app/routes/insights.port-performance.tsx");
  "routes/insights.staff-performance": typeof import("./app/routes/insights.staff-performance.tsx");
  "routes/insights.storage-utilization": typeof import("./app/routes/insights.storage-utilization.tsx");
  "routes/insights.replenishment": typeof import("./app/routes/insights.replenishment.tsx");
  "routes/insights.system-health": typeof import("./app/routes/insights.system-health.tsx");
  "routes/inbound": typeof import("./app/routes/inbound.tsx");
  "routes/inbound.overview": typeof import("./app/routes/inbound.overview.tsx");
  "routes/inbound.putaway": typeof import("./app/routes/inbound.putaway.tsx");
  "routes/outbound": typeof import("./app/routes/outbound.tsx");
  "routes/outbound.overview": typeof import("./app/routes/outbound.overview.tsx");
  "routes/outbound.picking": typeof import("./app/routes/outbound.picking.tsx");
  "routes/outbound.order-batching": typeof import("./app/routes/outbound.order-batching.tsx");
  "routes/outbound.picking-strategies": typeof import("./app/routes/outbound.picking-strategies.tsx");
  "routes/outbound.printing": typeof import("./app/routes/outbound.printing.tsx");
  "routes/inventory": typeof import("./app/routes/inventory.tsx");
  "routes/inventory.overview": typeof import("./app/routes/inventory.overview.tsx");
  "routes/inventory.inspection": typeof import("./app/routes/inventory.inspection.tsx");
  "routes/control-center": typeof import("./app/routes/control-center.tsx");
  "routes/control-center.warehouse-layout": typeof import("./app/routes/control-center.warehouse-layout.tsx");
  "routes/control-center.alert-monitoring": typeof import("./app/routes/control-center.alert-monitoring.tsx");
  "routes/control-center.orders-tracking": typeof import("./app/routes/control-center.orders-tracking.tsx");
  "routes/control-center.eoperator-console": typeof import("./app/routes/control-center.eoperator-console.tsx");
  "routes/control-center.maintenance": typeof import("./app/routes/control-center.maintenance.tsx");
  "routes/control-center.integration-logs": typeof import("./app/routes/control-center.integration-logs.tsx");
  "routes/control-center.system-logs": typeof import("./app/routes/control-center.system-logs.tsx");
  "routes/control-center.material-handling-logs": typeof import("./app/routes/control-center.material-handling-logs.tsx");
  "routes/configuration": typeof import("./app/routes/configuration.tsx");
  "routes/configuration.user-management": typeof import("./app/routes/configuration.user-management.tsx");
  "routes/configuration.language-settings": typeof import("./app/routes/configuration.language-settings.tsx");
  "routes/configuration.system-settings": typeof import("./app/routes/configuration.system-settings.tsx");
  "routes/configuration.inbound": typeof import("./app/routes/configuration.inbound.tsx");
  "routes/configuration.outbound": typeof import("./app/routes/configuration.outbound.tsx");
  "routes/configuration.inventory": typeof import("./app/routes/configuration.inventory.tsx");
  "routes/configuration.autostore": typeof import("./app/routes/configuration.autostore.tsx");
  "routes/configuration.general-setup": typeof import("./app/routes/configuration.general-setup.tsx");
  "routes/configuration.modules": typeof import("./app/routes/configuration.modules.tsx");
  "routes/configuration.orchestration": typeof import("./app/routes/configuration.orchestration.tsx");
  "routes/configuration.version-history": typeof import("./app/routes/configuration.version-history.tsx");
  "routes/profile.personal-information": typeof import("./app/routes/profile.personal-information.tsx");
  "routes/profile.system-preferences": typeof import("./app/routes/profile.system-preferences.tsx");
  "routes/profile.security": typeof import("./app/routes/profile.security.tsx");
};